// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/main/event/event.proto

package event

import (
	context "context"
	fmt "fmt"
	math "math"

	"main_service/config/grpc/proto/domain"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetByNameAndProductItemIDRequest struct {
	ProductItemId        string   `protobuf:"bytes,1,opt,name=product_item_id,json=productItemId,proto3" json:"product_item_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByNameAndProductItemIDRequest) Reset()         { *m = GetByNameAndProductItemIDRequest{} }
func (m *GetByNameAndProductItemIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByNameAndProductItemIDRequest) ProtoMessage()    {}
func (*GetByNameAndProductItemIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8db355aa907c5631, []int{0}
}

func (m *GetByNameAndProductItemIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByNameAndProductItemIDRequest.Unmarshal(m, b)
}
func (m *GetByNameAndProductItemIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByNameAndProductItemIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByNameAndProductItemIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByNameAndProductItemIDRequest.Merge(m, src)
}
func (m *GetByNameAndProductItemIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByNameAndProductItemIDRequest.Size(m)
}
func (m *GetByNameAndProductItemIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByNameAndProductItemIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByNameAndProductItemIDRequest proto.InternalMessageInfo

func (m *GetByNameAndProductItemIDRequest) GetProductItemId() string {
	if m != nil {
		return m.ProductItemId
	}
	return ""
}

func (m *GetByNameAndProductItemIDRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetByNameAndProductItemIDResponse struct {
	Events               []*domain.Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetByNameAndProductItemIDResponse) Reset()         { *m = GetByNameAndProductItemIDResponse{} }
func (m *GetByNameAndProductItemIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetByNameAndProductItemIDResponse) ProtoMessage()    {}
func (*GetByNameAndProductItemIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8db355aa907c5631, []int{1}
}

func (m *GetByNameAndProductItemIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByNameAndProductItemIDResponse.Unmarshal(m, b)
}
func (m *GetByNameAndProductItemIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByNameAndProductItemIDResponse.Marshal(b, m, deterministic)
}
func (m *GetByNameAndProductItemIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByNameAndProductItemIDResponse.Merge(m, src)
}
func (m *GetByNameAndProductItemIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetByNameAndProductItemIDResponse.Size(m)
}
func (m *GetByNameAndProductItemIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByNameAndProductItemIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByNameAndProductItemIDResponse proto.InternalMessageInfo

func (m *GetByNameAndProductItemIDResponse) GetEvents() []*domain.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*GetByNameAndProductItemIDRequest)(nil), "service.main.event.GetByNameAndProductItemIDRequest")
	proto.RegisterType((*GetByNameAndProductItemIDResponse)(nil), "service.main.event.GetByNameAndProductItemIDResponse")
}

func init() { proto.RegisterFile("service/main/event/event.proto", fileDescriptor_8db355aa907c5631) }

var fileDescriptor_8db355aa907c5631 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0x81, 0x90,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x42, 0x50, 0x79, 0x3d, 0x90, 0xbc, 0x1e, 0x58, 0x46,
	0x4a, 0x38, 0x25, 0x1f, 0xac, 0x1a, 0x42, 0x41, 0x14, 0x2a, 0xc5, 0x71, 0x29, 0xb8, 0xa7, 0x96,
	0x38, 0x55, 0xfa, 0x25, 0xe6, 0xa6, 0x3a, 0xe6, 0xa5, 0x04, 0x14, 0xe5, 0xa7, 0x94, 0x26, 0x97,
	0x78, 0x96, 0xa4, 0xe6, 0x7a, 0xba, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xa9, 0x71,
	0xf1, 0x17, 0x40, 0xc4, 0xe3, 0x33, 0x4b, 0x52, 0x73, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x78, 0x0b, 0x90, 0x94, 0xa7, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x81, 0x25, 0xc1, 0x6c, 0x25, 0x2f, 0x2e, 0x45, 0x3c, 0xe6, 0x17, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x0a, 0xa9, 0x72, 0xb1, 0x81, 0x9d, 0x58, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d,
	0xc4, 0xab, 0x07, 0x75, 0xa3, 0x2b, 0x48, 0x34, 0x08, 0x2a, 0x69, 0x34, 0x89, 0x91, 0x8b, 0x15,
	0x2c, 0x22, 0xd4, 0xc1, 0xc8, 0x25, 0x89, 0xd3, 0x58, 0x21, 0x13, 0x3d, 0x4c, 0xdf, 0xeb, 0x11,
	0xf2, 0xa5, 0x94, 0x29, 0x89, 0xba, 0x20, 0x6e, 0x77, 0x62, 0x8f, 0x62, 0x05, 0x2b, 0x4d, 0x62,
	0x03, 0x07, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xe2, 0xf8, 0xdc, 0x9b, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventClient is the client API for Event service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventClient interface {
	GetByNameAndProductItemID(ctx context.Context, in *GetByNameAndProductItemIDRequest, opts ...grpc.CallOption) (*GetByNameAndProductItemIDResponse, error)
}

type eventClient struct {
	cc *grpc.ClientConn
}

func NewEventClient(cc *grpc.ClientConn) EventClient {
	return &eventClient{cc}
}

func (c *eventClient) GetByNameAndProductItemID(ctx context.Context, in *GetByNameAndProductItemIDRequest, opts ...grpc.CallOption) (*GetByNameAndProductItemIDResponse, error) {
	out := new(GetByNameAndProductItemIDResponse)
	err := c.cc.Invoke(ctx, "/service.main.event.Event/GetByNameAndProductItemID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServer is the server API for Event service.
type EventServer interface {
	GetByNameAndProductItemID(context.Context, *GetByNameAndProductItemIDRequest) (*GetByNameAndProductItemIDResponse, error)
}

// UnimplementedEventServer can be embedded to have forward compatible implementations.
type UnimplementedEventServer struct {
}

func (*UnimplementedEventServer) GetByNameAndProductItemID(ctx context.Context, req *GetByNameAndProductItemIDRequest) (*GetByNameAndProductItemIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByNameAndProductItemID not implemented")
}

func RegisterEventServer(s *grpc.Server, srv EventServer) {
	s.RegisterService(&_Event_serviceDesc, srv)
}

func _Event_GetByNameAndProductItemID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByNameAndProductItemIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetByNameAndProductItemID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.main.event.Event/GetByNameAndProductItemID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetByNameAndProductItemID(ctx, req.(*GetByNameAndProductItemIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Event_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.main.event.Event",
	HandlerType: (*EventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByNameAndProductItemID",
			Handler:    _Event_GetByNameAndProductItemID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/main/event/event.proto",
}
