version: '3'

services:
  eos:
    image: eos_service:latest
    restart: always
    ports:
      - 50051
      - 4000
  app:
    image: main_service:latest
    restart: always
    ports:
      - 3001:3000
    env_file:
      - .env
    networks:
      - ipfsbr
      - default
  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_USER: '${POSTGREST_DB_USER}'
      POSTGRES_PASSWORD: '${POSTGREST_DB_PASSWORD}'
      POSTGRES_DB: '${POSTGREST_DB_NAME}'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  location:
    image: location_service:latest
    restart: always
    ports:
      - 3002:3006
  syncer:
    image: syncer:latest
    restart: always
    environment:
      DFUSE_API_KEY: server_956fa3438e0a2e717b5e886822b33c6a
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: '${POSTGREST_DB_USER}'
      PG_PASS: '${POSTGREST_DB_PASSWORD}'
      PG_DBNAME: '${POSTGREST_DB_NAME}'
      CONTRACT: dgybsotylyeq
      EOS_SERV_BASE_URL: http://eos:4000

  webapp:
    image: webapp:latest
    restart: always
    environment:
      PORT: 3000
      API_BASE_URL: https://api.goco.ml
    ports:
      - 3000:3000

networks:
  default:
    external:
      name: network-app
  ipfsbr:
    external:
      name: private-ipfs_ipfsbr