// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/main/system/system.proto

package system

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NextIDRequest struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextIDRequest) Reset()         { *m = NextIDRequest{} }
func (m *NextIDRequest) String() string { return proto.CompactTextString(m) }
func (*NextIDRequest) ProtoMessage()    {}
func (*NextIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dbc31762c7ef3fd, []int{0}
}

func (m *NextIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextIDRequest.Unmarshal(m, b)
}
func (m *NextIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextIDRequest.Marshal(b, m, deterministic)
}
func (m *NextIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextIDRequest.Merge(m, src)
}
func (m *NextIDRequest) XXX_Size() int {
	return xxx_messageInfo_NextIDRequest.Size(m)
}
func (m *NextIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NextIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NextIDRequest proto.InternalMessageInfo

func (m *NextIDRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type NextIDResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextIDResponse) Reset()         { *m = NextIDResponse{} }
func (m *NextIDResponse) String() string { return proto.CompactTextString(m) }
func (*NextIDResponse) ProtoMessage()    {}
func (*NextIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dbc31762c7ef3fd, []int{1}
}

func (m *NextIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextIDResponse.Unmarshal(m, b)
}
func (m *NextIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextIDResponse.Marshal(b, m, deterministic)
}
func (m *NextIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextIDResponse.Merge(m, src)
}
func (m *NextIDResponse) XXX_Size() int {
	return xxx_messageInfo_NextIDResponse.Size(m)
}
func (m *NextIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NextIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NextIDResponse proto.InternalMessageInfo

func (m *NextIDResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*NextIDRequest)(nil), "service.main.system.NextIDRequest")
	proto.RegisterType((*NextIDResponse)(nil), "service.main.system.NextIDResponse")
}

func init() { proto.RegisterFile("service/main/system/system.proto", fileDescriptor_6dbc31762c7ef3fd) }

var fileDescriptor_6dbc31762c7ef3fd = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x2f, 0xae, 0x2c, 0x2e, 0x49, 0xcd, 0x85,
	0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xc2, 0x50, 0x15, 0x7a, 0x20, 0x15, 0x7a, 0x10,
	0x29, 0x25, 0x55, 0x2e, 0x5e, 0xbf, 0xd4, 0x8a, 0x12, 0x4f, 0x97, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xc4, 0xa4, 0x9c, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x08, 0x47, 0x49, 0x81, 0x8b, 0x0f, 0xa6, 0xac, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55,
	0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0xaa, 0x88, 0x29, 0x33, 0xc5, 0x28, 0x9a, 0x8b, 0x2d, 0x18,
	0x6c, 0xa4, 0x50, 0x20, 0x17, 0x1b, 0x44, 0xad, 0x90, 0x92, 0x1e, 0x16, 0x2b, 0xf5, 0x50, 0xec,
	0x93, 0x52, 0xc6, 0xab, 0x06, 0x62, 0x99, 0x13, 0x47, 0x14, 0x1b, 0x44, 0x22, 0x89, 0x0d, 0xec,
	0x17, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xc1, 0xad, 0x46, 0xef, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemClient interface {
	NextID(ctx context.Context, in *NextIDRequest, opts ...grpc.CallOption) (*NextIDResponse, error)
}

type systemClient struct {
	cc *grpc.ClientConn
}

func NewSystemClient(cc *grpc.ClientConn) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) NextID(ctx context.Context, in *NextIDRequest, opts ...grpc.CallOption) (*NextIDResponse, error) {
	out := new(NextIDResponse)
	err := c.cc.Invoke(ctx, "/service.main.system.System/NextID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
type SystemServer interface {
	NextID(context.Context, *NextIDRequest) (*NextIDResponse, error)
}

// UnimplementedSystemServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (*UnimplementedSystemServer) NextID(ctx context.Context, req *NextIDRequest) (*NextIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextID not implemented")
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_NextID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).NextID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.main.system.System/NextID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).NextID(ctx, req.(*NextIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.main.system.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextID",
			Handler:    _System_NextID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/main/system/system.proto",
}
