// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/main/productitem/productitem.proto

package productitem

import (
	context "context"
	fmt "fmt"
	math "math"

	domain "main_service/config/grpc/proto/domain"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteRequest struct {
	ProductItemId        string   `protobuf:"bytes,1,opt,name=product_item_id,json=productItemId,proto3" json:"product_item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ea49bd3f493c4bc, []int{0}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetProductItemId() string {
	if m != nil {
		return m.ProductItemId
	}
	return ""
}

type GetByFacilityIDRequest struct {
	FacilityId           string             `protobuf:"bytes,1,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Order                *domain.QueryOrder `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Pagination           *domain.Pagination `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetByFacilityIDRequest) Reset()         { *m = GetByFacilityIDRequest{} }
func (m *GetByFacilityIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByFacilityIDRequest) ProtoMessage()    {}
func (*GetByFacilityIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ea49bd3f493c4bc, []int{1}
}

func (m *GetByFacilityIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByFacilityIDRequest.Unmarshal(m, b)
}
func (m *GetByFacilityIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByFacilityIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByFacilityIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByFacilityIDRequest.Merge(m, src)
}
func (m *GetByFacilityIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByFacilityIDRequest.Size(m)
}
func (m *GetByFacilityIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByFacilityIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByFacilityIDRequest proto.InternalMessageInfo

func (m *GetByFacilityIDRequest) GetFacilityId() string {
	if m != nil {
		return m.FacilityId
	}
	return ""
}

func (m *GetByFacilityIDRequest) GetOrder() *domain.QueryOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *GetByFacilityIDRequest) GetPagination() *domain.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetByFacilityIDResponse struct {
	ProductItems         []*domain.ProductItem `protobuf:"bytes,1,rep,name=product_items,json=productItems,proto3" json:"product_items,omitempty"`
	Count                int32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetByFacilityIDResponse) Reset()         { *m = GetByFacilityIDResponse{} }
func (m *GetByFacilityIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetByFacilityIDResponse) ProtoMessage()    {}
func (*GetByFacilityIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ea49bd3f493c4bc, []int{2}
}

func (m *GetByFacilityIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByFacilityIDResponse.Unmarshal(m, b)
}
func (m *GetByFacilityIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByFacilityIDResponse.Marshal(b, m, deterministic)
}
func (m *GetByFacilityIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByFacilityIDResponse.Merge(m, src)
}
func (m *GetByFacilityIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetByFacilityIDResponse.Size(m)
}
func (m *GetByFacilityIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByFacilityIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByFacilityIDResponse proto.InternalMessageInfo

func (m *GetByFacilityIDResponse) GetProductItems() []*domain.ProductItem {
	if m != nil {
		return m.ProductItems
	}
	return nil
}

func (m *GetByFacilityIDResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteRequest)(nil), "service.main.productitem.DeleteRequest")
	proto.RegisterType((*GetByFacilityIDRequest)(nil), "service.main.productitem.GetByFacilityIDRequest")
	proto.RegisterType((*GetByFacilityIDResponse)(nil), "service.main.productitem.GetByFacilityIDResponse")
}

func init() {
	proto.RegisterFile("service/main/productitem/productitem.proto", fileDescriptor_1ea49bd3f493c4bc)
}

var fileDescriptor_1ea49bd3f493c4bc = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x14, 0x4c, 0x25, 0x90, 0xf8, 0x6a, 0x83, 0x79, 0x18, 0x6d, 0x7a, 0x91, 0x70, 0xd0, 0xc6, 0x43,
	0xd1, 0x7a, 0xd0, 0x33, 0x10, 0x4d, 0x4f, 0x6a, 0x8f, 0x5e, 0x48, 0xed, 0x3e, 0xcd, 0x26, 0xd0,
	0xad, 0xbb, 0x5b, 0x12, 0xbe, 0xc4, 0xbf, 0x35, 0x06, 0xb6, 0xc0, 0xa2, 0x70, 0xf0, 0xd4, 0xee,
	0xbc, 0x99, 0xd9, 0x37, 0x99, 0x85, 0x2b, 0x45, 0x72, 0xc6, 0x73, 0xea, 0x4f, 0x33, 0x5e, 0xf4,
	0x4b, 0x29, 0x58, 0x95, 0x6b, 0xae, 0x69, 0x6a, 0xff, 0x47, 0xa5, 0x14, 0x5a, 0xa0, 0x5f, 0x73,
	0xa3, 0x05, 0x37, 0xb2, 0xe6, 0x41, 0x87, 0x89, 0xa5, 0xde, 0x7c, 0x0c, 0xbd, 0x77, 0x07, 0xde,
	0x88, 0x26, 0xa4, 0x29, 0xa5, 0xcf, 0x8a, 0x94, 0xc6, 0x0b, 0x68, 0xd7, 0xa2, 0xf1, 0x42, 0x35,
	0xe6, 0xcc, 0x77, 0xba, 0x4e, 0x78, 0x98, 0x7a, 0x35, 0x9c, 0x68, 0x9a, 0x26, 0xac, 0xf7, 0xe5,
	0xc0, 0xe9, 0x23, 0xe9, 0xc1, 0xfc, 0x21, 0xcb, 0xf9, 0x84, 0xeb, 0x79, 0x32, 0x5a, 0x59, 0x9c,
	0x83, 0xfb, 0x5e, 0x83, 0x1b, 0x39, 0xac, 0xa0, 0x84, 0x61, 0x08, 0x4d, 0x21, 0x19, 0x49, 0xff,
	0xa0, 0xeb, 0x84, 0x6e, 0x8c, 0x51, 0xbd, 0xd2, 0x4b, 0x45, 0x72, 0xfe, 0xb4, 0x98, 0xa4, 0x86,
	0x80, 0x31, 0x40, 0x99, 0x7d, 0xf0, 0x22, 0xd3, 0x5c, 0x14, 0x7e, 0x63, 0x9b, 0xfe, 0xbc, 0x9e,
	0xa4, 0x16, 0xab, 0xc7, 0xe1, 0xec, 0xcf, 0x62, 0xaa, 0x14, 0x85, 0x22, 0xbc, 0x07, 0xcf, 0x0e,
	0xa7, 0x7c, 0xa7, 0xdb, 0x08, 0xdd, 0xb8, 0xb3, 0x76, 0xdc, 0x44, 0x4c, 0x8f, 0xac, 0xbc, 0x0a,
	0x4f, 0xa0, 0x99, 0x8b, 0xaa, 0xd0, 0xcb, 0x95, 0x9b, 0xa9, 0x39, 0xc4, 0xdf, 0x0e, 0xb8, 0x96,
	0x06, 0x63, 0x68, 0x0d, 0x25, 0x65, 0x9a, 0x70, 0x97, 0x65, 0xb0, 0x0b, 0xc4, 0x21, 0xb4, 0x4c,
	0x03, 0x78, 0x19, 0xed, 0xeb, 0x2e, 0xda, 0xea, 0x28, 0x38, 0x5e, 0xf9, 0xac, 0x83, 0xcd, 0xa0,
	0xfd, 0x2b, 0x33, 0x5e, 0xef, 0x77, 0xdb, 0xdd, 0x5b, 0x70, 0xf3, 0x0f, 0x85, 0xb9, 0x77, 0xe0,
	0xbd, 0xba, 0x16, 0xed, 0xad, 0xb5, 0x7c, 0x54, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x51,
	0x57, 0x04, 0x3c, 0xb1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductItemClient is the client API for ProductItem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductItemClient interface {
	Create(ctx context.Context, in *domain.ProductItem, opts ...grpc.CallOption) (*domain.ProductItem, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*domain.Response, error)
	GetByFacilityID(ctx context.Context, in *GetByFacilityIDRequest, opts ...grpc.CallOption) (*GetByFacilityIDResponse, error)
}

type productItemClient struct {
	cc *grpc.ClientConn
}

func NewProductItemClient(cc *grpc.ClientConn) ProductItemClient {
	return &productItemClient{cc}
}

func (c *productItemClient) Create(ctx context.Context, in *domain.ProductItem, opts ...grpc.CallOption) (*domain.ProductItem, error) {
	out := new(domain.ProductItem)
	err := c.cc.Invoke(ctx, "/service.main.productitem.ProductItem/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productItemClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.main.productitem.ProductItem/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productItemClient) GetByFacilityID(ctx context.Context, in *GetByFacilityIDRequest, opts ...grpc.CallOption) (*GetByFacilityIDResponse, error) {
	out := new(GetByFacilityIDResponse)
	err := c.cc.Invoke(ctx, "/service.main.productitem.ProductItem/GetByFacilityID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductItemServer is the server API for ProductItem service.
type ProductItemServer interface {
	Create(context.Context, *domain.ProductItem) (*domain.ProductItem, error)
	Delete(context.Context, *DeleteRequest) (*domain.Response, error)
	GetByFacilityID(context.Context, *GetByFacilityIDRequest) (*GetByFacilityIDResponse, error)
}

// UnimplementedProductItemServer can be embedded to have forward compatible implementations.
type UnimplementedProductItemServer struct {
}

func (*UnimplementedProductItemServer) Create(ctx context.Context, req *domain.ProductItem) (*domain.ProductItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProductItemServer) Delete(ctx context.Context, req *DeleteRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedProductItemServer) GetByFacilityID(ctx context.Context, req *GetByFacilityIDRequest) (*GetByFacilityIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByFacilityID not implemented")
}

func RegisterProductItemServer(s *grpc.Server, srv ProductItemServer) {
	s.RegisterService(&_ProductItem_serviceDesc, srv)
}

func _ProductItem_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.ProductItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductItemServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.main.productitem.ProductItem/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductItemServer).Create(ctx, req.(*domain.ProductItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductItem_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductItemServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.main.productitem.ProductItem/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductItemServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductItem_GetByFacilityID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByFacilityIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductItemServer).GetByFacilityID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.main.productitem.ProductItem/GetByFacilityID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductItemServer).GetByFacilityID(ctx, req.(*GetByFacilityIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductItem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.main.productitem.ProductItem",
	HandlerType: (*ProductItemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductItem_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProductItem_Delete_Handler,
		},
		{
			MethodName: "GetByFacilityID",
			Handler:    _ProductItem_GetByFacilityID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/main/productitem/productitem.proto",
}
