// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/eos/eos.proto

package eos

import (
	context "context"
	fmt "fmt"
	math "math"

	domain "main_service/config/grpc/proto/domain"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDRequest) Reset()         { *m = GetByIDRequest{} }
func (m *GetByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIDRequest) ProtoMessage()    {}
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{0}
}

func (m *GetByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDRequest.Unmarshal(m, b)
}
func (m *GetByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDRequest.Merge(m, src)
}
func (m *GetByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIDRequest.Size(m)
}
func (m *GetByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDRequest proto.InternalMessageInfo

func (m *GetByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NewProductRequest struct {
	Product              *domain.Product    `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	EosAccount           *domain.EosAccount `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NewProductRequest) Reset()         { *m = NewProductRequest{} }
func (m *NewProductRequest) String() string { return proto.CompactTextString(m) }
func (*NewProductRequest) ProtoMessage()    {}
func (*NewProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{1}
}

func (m *NewProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProductRequest.Unmarshal(m, b)
}
func (m *NewProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProductRequest.Marshal(b, m, deterministic)
}
func (m *NewProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProductRequest.Merge(m, src)
}
func (m *NewProductRequest) XXX_Size() int {
	return xxx_messageInfo_NewProductRequest.Size(m)
}
func (m *NewProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewProductRequest proto.InternalMessageInfo

func (m *NewProductRequest) GetProduct() *domain.Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *NewProductRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type DeleteProductRequest struct {
	ProductId            string             `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	EosAccount           *domain.EosAccount `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{2}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *DeleteProductRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type UpdateProductNameRequest struct {
	ProductId            string             `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EosAccount           *domain.EosAccount `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateProductNameRequest) Reset()         { *m = UpdateProductNameRequest{} }
func (m *UpdateProductNameRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductNameRequest) ProtoMessage()    {}
func (*UpdateProductNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{3}
}

func (m *UpdateProductNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductNameRequest.Unmarshal(m, b)
}
func (m *UpdateProductNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductNameRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductNameRequest.Merge(m, src)
}
func (m *UpdateProductNameRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductNameRequest.Size(m)
}
func (m *UpdateProductNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductNameRequest proto.InternalMessageInfo

func (m *UpdateProductNameRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *UpdateProductNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProductNameRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type NewProductItemRequest struct {
	ProductItem          *domain.ProductItem `protobuf:"bytes,1,opt,name=product_item,json=productItem,proto3" json:"product_item,omitempty"`
	EosAccount           *domain.EosAccount  `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NewProductItemRequest) Reset()         { *m = NewProductItemRequest{} }
func (m *NewProductItemRequest) String() string { return proto.CompactTextString(m) }
func (*NewProductItemRequest) ProtoMessage()    {}
func (*NewProductItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{4}
}

func (m *NewProductItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProductItemRequest.Unmarshal(m, b)
}
func (m *NewProductItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProductItemRequest.Marshal(b, m, deterministic)
}
func (m *NewProductItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProductItemRequest.Merge(m, src)
}
func (m *NewProductItemRequest) XXX_Size() int {
	return xxx_messageInfo_NewProductItemRequest.Size(m)
}
func (m *NewProductItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProductItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewProductItemRequest proto.InternalMessageInfo

func (m *NewProductItemRequest) GetProductItem() *domain.ProductItem {
	if m != nil {
		return m.ProductItem
	}
	return nil
}

func (m *NewProductItemRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type DeleteProductItemRequest struct {
	ProductItemId        string             `protobuf:"bytes,1,opt,name=product_item_id,json=productItemId,proto3" json:"product_item_id,omitempty"`
	EosAccount           *domain.EosAccount `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DeleteProductItemRequest) Reset()         { *m = DeleteProductItemRequest{} }
func (m *DeleteProductItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductItemRequest) ProtoMessage()    {}
func (*DeleteProductItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{5}
}

func (m *DeleteProductItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductItemRequest.Unmarshal(m, b)
}
func (m *DeleteProductItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductItemRequest.Merge(m, src)
}
func (m *DeleteProductItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductItemRequest.Size(m)
}
func (m *DeleteProductItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductItemRequest proto.InternalMessageInfo

func (m *DeleteProductItemRequest) GetProductItemId() string {
	if m != nil {
		return m.ProductItemId
	}
	return ""
}

func (m *DeleteProductItemRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type NewProductImageRequest struct {
	ProductImage         *domain.ProductImage `protobuf:"bytes,1,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	EosAccount           *domain.EosAccount   `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NewProductImageRequest) Reset()         { *m = NewProductImageRequest{} }
func (m *NewProductImageRequest) String() string { return proto.CompactTextString(m) }
func (*NewProductImageRequest) ProtoMessage()    {}
func (*NewProductImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{6}
}

func (m *NewProductImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProductImageRequest.Unmarshal(m, b)
}
func (m *NewProductImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProductImageRequest.Marshal(b, m, deterministic)
}
func (m *NewProductImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProductImageRequest.Merge(m, src)
}
func (m *NewProductImageRequest) XXX_Size() int {
	return xxx_messageInfo_NewProductImageRequest.Size(m)
}
func (m *NewProductImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProductImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewProductImageRequest proto.InternalMessageInfo

func (m *NewProductImageRequest) GetProductImage() *domain.ProductImage {
	if m != nil {
		return m.ProductImage
	}
	return nil
}

func (m *NewProductImageRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type DeleteAllProductImagesRequest struct {
	ProductId            string             `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	EosAccount           *domain.EosAccount `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DeleteAllProductImagesRequest) Reset()         { *m = DeleteAllProductImagesRequest{} }
func (m *DeleteAllProductImagesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllProductImagesRequest) ProtoMessage()    {}
func (*DeleteAllProductImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{7}
}

func (m *DeleteAllProductImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllProductImagesRequest.Unmarshal(m, b)
}
func (m *DeleteAllProductImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllProductImagesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllProductImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllProductImagesRequest.Merge(m, src)
}
func (m *DeleteAllProductImagesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllProductImagesRequest.Size(m)
}
func (m *DeleteAllProductImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllProductImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllProductImagesRequest proto.InternalMessageInfo

func (m *DeleteAllProductImagesRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *DeleteAllProductImagesRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type NewEventRequest struct {
	Event                *domain.Event      `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	EosAccount           *domain.EosAccount `protobuf:"bytes,2,opt,name=eos_account,json=eosAccount,proto3" json:"eos_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NewEventRequest) Reset()         { *m = NewEventRequest{} }
func (m *NewEventRequest) String() string { return proto.CompactTextString(m) }
func (*NewEventRequest) ProtoMessage()    {}
func (*NewEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{8}
}

func (m *NewEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEventRequest.Unmarshal(m, b)
}
func (m *NewEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEventRequest.Marshal(b, m, deterministic)
}
func (m *NewEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEventRequest.Merge(m, src)
}
func (m *NewEventRequest) XXX_Size() int {
	return xxx_messageInfo_NewEventRequest.Size(m)
}
func (m *NewEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewEventRequest proto.InternalMessageInfo

func (m *NewEventRequest) GetEvent() *domain.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *NewEventRequest) GetEosAccount() *domain.EosAccount {
	if m != nil {
		return m.EosAccount
	}
	return nil
}

type GetPubFromPrivRequest struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPubFromPrivRequest) Reset()         { *m = GetPubFromPrivRequest{} }
func (m *GetPubFromPrivRequest) String() string { return proto.CompactTextString(m) }
func (*GetPubFromPrivRequest) ProtoMessage()    {}
func (*GetPubFromPrivRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{9}
}

func (m *GetPubFromPrivRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPubFromPrivRequest.Unmarshal(m, b)
}
func (m *GetPubFromPrivRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPubFromPrivRequest.Marshal(b, m, deterministic)
}
func (m *GetPubFromPrivRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPubFromPrivRequest.Merge(m, src)
}
func (m *GetPubFromPrivRequest) XXX_Size() int {
	return xxx_messageInfo_GetPubFromPrivRequest.Size(m)
}
func (m *GetPubFromPrivRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPubFromPrivRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPubFromPrivRequest proto.InternalMessageInfo

func (m *GetPubFromPrivRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type GetPubFromPrivResponse struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPubFromPrivResponse) Reset()         { *m = GetPubFromPrivResponse{} }
func (m *GetPubFromPrivResponse) String() string { return proto.CompactTextString(m) }
func (*GetPubFromPrivResponse) ProtoMessage()    {}
func (*GetPubFromPrivResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{10}
}

func (m *GetPubFromPrivResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPubFromPrivResponse.Unmarshal(m, b)
}
func (m *GetPubFromPrivResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPubFromPrivResponse.Marshal(b, m, deterministic)
}
func (m *GetPubFromPrivResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPubFromPrivResponse.Merge(m, src)
}
func (m *GetPubFromPrivResponse) XXX_Size() int {
	return xxx_messageInfo_GetPubFromPrivResponse.Size(m)
}
func (m *GetPubFromPrivResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPubFromPrivResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPubFromPrivResponse proto.InternalMessageInfo

func (m *GetPubFromPrivResponse) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type GetNameFromPubRequest struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNameFromPubRequest) Reset()         { *m = GetNameFromPubRequest{} }
func (m *GetNameFromPubRequest) String() string { return proto.CompactTextString(m) }
func (*GetNameFromPubRequest) ProtoMessage()    {}
func (*GetNameFromPubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{11}
}

func (m *GetNameFromPubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNameFromPubRequest.Unmarshal(m, b)
}
func (m *GetNameFromPubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNameFromPubRequest.Marshal(b, m, deterministic)
}
func (m *GetNameFromPubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNameFromPubRequest.Merge(m, src)
}
func (m *GetNameFromPubRequest) XXX_Size() int {
	return xxx_messageInfo_GetNameFromPubRequest.Size(m)
}
func (m *GetNameFromPubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNameFromPubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNameFromPubRequest proto.InternalMessageInfo

func (m *GetNameFromPubRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type GetNameFromPubResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNameFromPubResponse) Reset()         { *m = GetNameFromPubResponse{} }
func (m *GetNameFromPubResponse) String() string { return proto.CompactTextString(m) }
func (*GetNameFromPubResponse) ProtoMessage()    {}
func (*GetNameFromPubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{12}
}

func (m *GetNameFromPubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNameFromPubResponse.Unmarshal(m, b)
}
func (m *GetNameFromPubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNameFromPubResponse.Marshal(b, m, deterministic)
}
func (m *GetNameFromPubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNameFromPubResponse.Merge(m, src)
}
func (m *GetNameFromPubResponse) XXX_Size() int {
	return xxx_messageInfo_GetNameFromPubResponse.Size(m)
}
func (m *GetNameFromPubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNameFromPubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNameFromPubResponse proto.InternalMessageInfo

func (m *GetNameFromPubResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPubFromNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPubFromNameRequest) Reset()         { *m = GetPubFromNameRequest{} }
func (m *GetPubFromNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetPubFromNameRequest) ProtoMessage()    {}
func (*GetPubFromNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{13}
}

func (m *GetPubFromNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPubFromNameRequest.Unmarshal(m, b)
}
func (m *GetPubFromNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPubFromNameRequest.Marshal(b, m, deterministic)
}
func (m *GetPubFromNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPubFromNameRequest.Merge(m, src)
}
func (m *GetPubFromNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetPubFromNameRequest.Size(m)
}
func (m *GetPubFromNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPubFromNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPubFromNameRequest proto.InternalMessageInfo

func (m *GetPubFromNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPubFromNameResponse struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPubFromNameResponse) Reset()         { *m = GetPubFromNameResponse{} }
func (m *GetPubFromNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetPubFromNameResponse) ProtoMessage()    {}
func (*GetPubFromNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6634401e8d86e904, []int{14}
}

func (m *GetPubFromNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPubFromNameResponse.Unmarshal(m, b)
}
func (m *GetPubFromNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPubFromNameResponse.Marshal(b, m, deterministic)
}
func (m *GetPubFromNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPubFromNameResponse.Merge(m, src)
}
func (m *GetPubFromNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetPubFromNameResponse.Size(m)
}
func (m *GetPubFromNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPubFromNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPubFromNameResponse proto.InternalMessageInfo

func (m *GetPubFromNameResponse) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GetByIDRequest)(nil), "service.eos.GetByIDRequest")
	proto.RegisterType((*NewProductRequest)(nil), "service.eos.NewProductRequest")
	proto.RegisterType((*DeleteProductRequest)(nil), "service.eos.DeleteProductRequest")
	proto.RegisterType((*UpdateProductNameRequest)(nil), "service.eos.UpdateProductNameRequest")
	proto.RegisterType((*NewProductItemRequest)(nil), "service.eos.NewProductItemRequest")
	proto.RegisterType((*DeleteProductItemRequest)(nil), "service.eos.DeleteProductItemRequest")
	proto.RegisterType((*NewProductImageRequest)(nil), "service.eos.NewProductImageRequest")
	proto.RegisterType((*DeleteAllProductImagesRequest)(nil), "service.eos.DeleteAllProductImagesRequest")
	proto.RegisterType((*NewEventRequest)(nil), "service.eos.NewEventRequest")
	proto.RegisterType((*GetPubFromPrivRequest)(nil), "service.eos.GetPubFromPrivRequest")
	proto.RegisterType((*GetPubFromPrivResponse)(nil), "service.eos.GetPubFromPrivResponse")
	proto.RegisterType((*GetNameFromPubRequest)(nil), "service.eos.GetNameFromPubRequest")
	proto.RegisterType((*GetNameFromPubResponse)(nil), "service.eos.GetNameFromPubResponse")
	proto.RegisterType((*GetPubFromNameRequest)(nil), "service.eos.GetPubFromNameRequest")
	proto.RegisterType((*GetPubFromNameResponse)(nil), "service.eos.GetPubFromNameResponse")
}

func init() { proto.RegisterFile("service/eos/eos.proto", fileDescriptor_6634401e8d86e904) }

var fileDescriptor_6634401e8d86e904 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x37, 0x06, 0xf4, 0x86, 0xae, 0xcc, 0xfb, 0x50, 0x55, 0x18, 0x8c, 0x56, 0x20, 0xbe,
	0xd4, 0xc1, 0x26, 0x8d, 0x8f, 0x87, 0x89, 0x4d, 0x6b, 0xc7, 0x04, 0xea, 0xa6, 0x4d, 0x20, 0xc1,
	0xcb, 0x94, 0xb6, 0x57, 0x28, 0xac, 0xa9, 0x43, 0xec, 0xb4, 0xea, 0x2b, 0xe2, 0x81, 0xbf, 0xc6,
	0xbf, 0x42, 0x71, 0xec, 0xd4, 0x49, 0x9c, 0x0d, 0x45, 0xe2, 0x61, 0x5a, 0x72, 0x73, 0xee, 0xb9,
	0xe7, 0x5e, 0xdb, 0xc7, 0x85, 0x55, 0x86, 0xfe, 0xd8, 0xe9, 0xe3, 0x26, 0x52, 0x16, 0xfe, 0xb5,
	0x3c, 0x9f, 0x72, 0x4a, 0x2c, 0x19, 0x6e, 0x21, 0x65, 0xf5, 0xe5, 0x01, 0x75, 0x6d, 0x67, 0xb4,
	0x19, 0xfd, 0x8b, 0x10, 0x8d, 0x0d, 0x58, 0x3c, 0x44, 0xbe, 0x3f, 0x3d, 0x3a, 0x38, 0xc5, 0x1f,
	0x01, 0x32, 0x4e, 0x16, 0x61, 0xce, 0x19, 0xd4, 0x4a, 0x1b, 0xa5, 0xc7, 0xe5, 0xd3, 0x39, 0x67,
	0xd0, 0x60, 0xb0, 0xd4, 0xc5, 0xc9, 0x89, 0x4f, 0x07, 0x41, 0x9f, 0x2b, 0xd0, 0x13, 0xb8, 0xe1,
	0x45, 0x11, 0x81, 0xb4, 0xb6, 0xaa, 0x2d, 0x49, 0xab, 0x80, 0xea, 0x3b, 0xd9, 0x06, 0x0b, 0x29,
	0x3b, 0xb7, 0xfb, 0x7d, 0x1a, 0x8c, 0x78, 0x6d, 0x4e, 0xc0, 0x89, 0x82, 0xb7, 0x29, 0xdb, 0x8b,
	0xbe, 0x9c, 0x02, 0xc6, 0xcf, 0x8d, 0xef, 0xb0, 0x72, 0x80, 0x43, 0xe4, 0x98, 0xaa, 0xbb, 0x0e,
	0x20, 0x79, 0xcf, 0x63, 0x91, 0x65, 0x19, 0x39, 0x1a, 0x14, 0xab, 0xf5, 0xb3, 0x04, 0xb5, 0x4f,
	0xde, 0xc0, 0x8e, 0x8b, 0x75, 0x6d, 0x17, 0xcd, 0x05, 0xe7, 0xd3, 0x05, 0x09, 0x5c, 0x1b, 0xd9,
	0x2e, 0x4a, 0x25, 0xe2, 0xb9, 0x98, 0x88, 0x5f, 0x25, 0x58, 0x9d, 0x8d, 0xf9, 0x88, 0xa3, 0xab,
	0x14, 0xec, 0xc0, 0xad, 0x58, 0x01, 0x47, 0x57, 0xce, 0x7b, 0x39, 0x35, 0x6f, 0x91, 0x61, 0x79,
	0xb3, 0x97, 0x62, 0x32, 0x26, 0x50, 0x4b, 0xcc, 0x5d, 0x17, 0xf2, 0x08, 0xaa, 0xba, 0x90, 0xd9,
	0x02, 0x54, 0xb4, 0xb2, 0x45, 0x17, 0xe1, 0x77, 0x09, 0xd6, 0xb4, 0xfe, 0x5d, 0xfb, 0x5b, 0xbc,
	0x04, 0x6f, 0xa0, 0x12, 0xd7, 0x0d, 0xe3, 0x72, 0x02, 0x2b, 0xe9, 0x09, 0x88, 0x1c, 0x35, 0x2b,
	0xf1, 0x56, 0x4c, 0x0a, 0x83, 0xf5, 0x68, 0x06, 0x7b, 0xc3, 0xa1, 0xce, 0xcd, 0xfe, 0xe7, 0x26,
	0xbc, 0x80, 0x6a, 0x17, 0x27, 0xed, 0x31, 0x8e, 0xe2, 0xbd, 0xde, 0x84, 0x05, 0x0c, 0xdf, 0x65,
	0xbf, 0x95, 0x98, 0x41, 0x80, 0xa2, 0x6f, 0xc5, 0x8a, 0xbd, 0x86, 0xd5, 0x43, 0xe4, 0x27, 0x41,
	0xaf, 0xe3, 0x53, 0xf7, 0xc4, 0x77, 0xc6, 0xaa, 0xe4, 0x7d, 0xb0, 0x3c, 0xdf, 0x19, 0xdb, 0x1c,
	0xcf, 0x2f, 0x70, 0x2a, 0x5b, 0x03, 0x19, 0xfa, 0x80, 0xd3, 0xc6, 0x2b, 0x58, 0x4b, 0x67, 0x32,
	0x8f, 0x8e, 0x18, 0x8a, 0xa1, 0x04, 0xbd, 0xa1, 0xd3, 0xd7, 0x32, 0xcb, 0x51, 0x24, 0x4c, 0xdc,
	0x11, 0x25, 0xc3, 0x93, 0x25, 0x32, 0x83, 0x9e, 0x3e, 0xcc, 0x4b, 0xf2, 0x9e, 0x8b, 0x82, 0x89,
	0x3c, 0x59, 0xd0, 0x70, 0xf4, 0x1a, 0xcf, 0xf4, 0xc6, 0xf4, 0x63, 0x6c, 0x02, 0x27, 0x7a, 0x89,
	0xc0, 0xff, 0xd4, 0xcb, 0xd6, 0x9f, 0x32, 0xcc, 0xb7, 0x8f, 0xcf, 0xc8, 0x0b, 0xa8, 0x84, 0x6b,
	0x76, 0x7c, 0x26, 0xe7, 0x4a, 0x2c, 0x35, 0xf7, 0xae, 0x33, 0xac, 0x1b, 0x16, 0x81, 0xbc, 0x04,
	0xab, 0x8b, 0x93, 0x8e, 0xdd, 0x77, 0x86, 0x0e, 0x9f, 0x92, 0xdb, 0x0a, 0xa2, 0x22, 0xf5, 0x38,
	0x12, 0x6b, 0x79, 0x0b, 0xe4, 0x10, 0xb9, 0x02, 0xb4, 0x8f, 0xcf, 0x42, 0xa5, 0xc4, 0x40, 0x5e,
	0xcf, 0xb0, 0x91, 0x77, 0x50, 0xd5, 0x72, 0x43, 0x93, 0x27, 0x77, 0x5a, 0xda, 0x95, 0xd0, 0x4a,
	0x5a, 0xbf, 0x81, 0x61, 0x17, 0x60, 0x76, 0x2a, 0xc9, 0xbd, 0x44, 0x72, 0xe6, 0x56, 0x30, 0xa8,
	0x3f, 0x80, 0x4a, 0xc2, 0x4f, 0xc8, 0x83, 0x04, 0x85, 0xc9, 0xe3, 0x0d, 0x2c, 0x1f, 0x61, 0x29,
	0x63, 0xd0, 0xe4, 0x61, 0x82, 0x29, 0xcf, 0xc0, 0x0d, 0x6c, 0xbb, 0xe2, 0xca, 0x93, 0xd0, 0xab,
	0x87, 0x92, 0xbe, 0xd9, 0x48, 0x07, 0x16, 0x93, 0x4e, 0x4d, 0x1a, 0x39, 0x73, 0xd1, 0xdc, 0xd3,
	0xdc, 0x55, 0xc6, 0x6b, 0x53, 0x5d, 0xe5, 0x79, 0xb1, 0x81, 0xad, 0x23, 0xf6, 0x89, 0x06, 0xbd,
	0xba, 0x33, 0xd3, 0x1d, 0x42, 0xde, 0x0b, 0x23, 0xd2, 0x7d, 0x8f, 0x34, 0xf3, 0xda, 0xd3, 0x5c,
	0xda, 0xa0, 0xe8, 0x33, 0xac, 0x99, 0x7d, 0x94, 0x3c, 0x35, 0x34, 0x99, 0x63, 0xb6, 0xc6, 0x13,
	0x71, 0x53, 0x59, 0x25, 0xb9, 0x9b, 0x96, 0xa6, 0x3b, 0xa8, 0x21, 0xf7, 0x4b, 0xb4, 0xf6, 0x33,
	0xff, 0x4a, 0xad, 0x9d, 0xd1, 0x16, 0xeb, 0xcd, 0x4b, 0x31, 0x09, 0x6a, 0xcd, 0xa9, 0xb2, 0xd4,
	0x59, 0xfb, 0xcb, 0x52, 0x9b, 0xac, 0x2e, 0xa1, 0x5a, 0x6c, 0xfe, 0x3c, 0xd5, 0xfa, 0xce, 0x6f,
	0x5e, 0x8a, 0x89, 0xa8, 0xf7, 0x17, 0xbe, 0xce, 0x23, 0x65, 0xbd, 0xeb, 0xe2, 0xd7, 0xe0, 0xf6,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x31, 0x81, 0x0f, 0x48, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EOSClient is the client API for EOS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EOSClient interface {
	NewEOSAccount(ctx context.Context, in *domain.Nil, opts ...grpc.CallOption) (*domain.EosAccount, error)
	NewFacility(ctx context.Context, in *domain.Facility, opts ...grpc.CallOption) (*domain.Response, error)
	GetFacilityEOSName(ctx context.Context, in *domain.EosAccount, opts ...grpc.CallOption) (*domain.Facility, error)
	GetFacilityByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*domain.Facility, error)
	NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*domain.Response, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*domain.Response, error)
	UpdateProductName(ctx context.Context, in *UpdateProductNameRequest, opts ...grpc.CallOption) (*domain.Response, error)
	GetProductByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*domain.Product, error)
	NewProductItem(ctx context.Context, in *NewProductItemRequest, opts ...grpc.CallOption) (*domain.Response, error)
	DeleteProductItem(ctx context.Context, in *DeleteProductItemRequest, opts ...grpc.CallOption) (*domain.Response, error)
	GetProductItemByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*domain.ProductItem, error)
	NewProductImage(ctx context.Context, in *NewProductImageRequest, opts ...grpc.CallOption) (*domain.Response, error)
	DeleteAllProductImages(ctx context.Context, in *DeleteAllProductImagesRequest, opts ...grpc.CallOption) (*domain.Response, error)
	NewEvent(ctx context.Context, in *NewEventRequest, opts ...grpc.CallOption) (*domain.Response, error)
	GetPubFromPriv(ctx context.Context, in *GetPubFromPrivRequest, opts ...grpc.CallOption) (*GetPubFromPrivResponse, error)
	GetNameFromPub(ctx context.Context, in *GetNameFromPubRequest, opts ...grpc.CallOption) (*GetNameFromPubResponse, error)
	GetPubFromName(ctx context.Context, in *GetPubFromNameRequest, opts ...grpc.CallOption) (*GetPubFromNameResponse, error)
}

type eOSClient struct {
	cc *grpc.ClientConn
}

func NewEOSClient(cc *grpc.ClientConn) EOSClient {
	return &eOSClient{cc}
}

func (c *eOSClient) NewEOSAccount(ctx context.Context, in *domain.Nil, opts ...grpc.CallOption) (*domain.EosAccount, error) {
	out := new(domain.EosAccount)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/NewEOSAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) NewFacility(ctx context.Context, in *domain.Facility, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/NewFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) GetFacilityEOSName(ctx context.Context, in *domain.EosAccount, opts ...grpc.CallOption) (*domain.Facility, error) {
	out := new(domain.Facility)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/GetFacilityEOSName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) GetFacilityByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*domain.Facility, error) {
	out := new(domain.Facility)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/GetFacilityByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/NewProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) UpdateProductName(ctx context.Context, in *UpdateProductNameRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/UpdateProductName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) GetProductByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*domain.Product, error) {
	out := new(domain.Product)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/GetProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) NewProductItem(ctx context.Context, in *NewProductItemRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/NewProductItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) DeleteProductItem(ctx context.Context, in *DeleteProductItemRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/DeleteProductItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) GetProductItemByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*domain.ProductItem, error) {
	out := new(domain.ProductItem)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/GetProductItemByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) NewProductImage(ctx context.Context, in *NewProductImageRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/NewProductImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) DeleteAllProductImages(ctx context.Context, in *DeleteAllProductImagesRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/DeleteAllProductImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) NewEvent(ctx context.Context, in *NewEventRequest, opts ...grpc.CallOption) (*domain.Response, error) {
	out := new(domain.Response)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/NewEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) GetPubFromPriv(ctx context.Context, in *GetPubFromPrivRequest, opts ...grpc.CallOption) (*GetPubFromPrivResponse, error) {
	out := new(GetPubFromPrivResponse)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/GetPubFromPriv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) GetNameFromPub(ctx context.Context, in *GetNameFromPubRequest, opts ...grpc.CallOption) (*GetNameFromPubResponse, error) {
	out := new(GetNameFromPubResponse)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/GetNameFromPub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eOSClient) GetPubFromName(ctx context.Context, in *GetPubFromNameRequest, opts ...grpc.CallOption) (*GetPubFromNameResponse, error) {
	out := new(GetPubFromNameResponse)
	err := c.cc.Invoke(ctx, "/service.eos.EOS/GetPubFromName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EOSServer is the server API for EOS service.
type EOSServer interface {
	NewEOSAccount(context.Context, *domain.Nil) (*domain.EosAccount, error)
	NewFacility(context.Context, *domain.Facility) (*domain.Response, error)
	GetFacilityEOSName(context.Context, *domain.EosAccount) (*domain.Facility, error)
	GetFacilityByID(context.Context, *GetByIDRequest) (*domain.Facility, error)
	NewProduct(context.Context, *NewProductRequest) (*domain.Response, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*domain.Response, error)
	UpdateProductName(context.Context, *UpdateProductNameRequest) (*domain.Response, error)
	GetProductByID(context.Context, *GetByIDRequest) (*domain.Product, error)
	NewProductItem(context.Context, *NewProductItemRequest) (*domain.Response, error)
	DeleteProductItem(context.Context, *DeleteProductItemRequest) (*domain.Response, error)
	GetProductItemByID(context.Context, *GetByIDRequest) (*domain.ProductItem, error)
	NewProductImage(context.Context, *NewProductImageRequest) (*domain.Response, error)
	DeleteAllProductImages(context.Context, *DeleteAllProductImagesRequest) (*domain.Response, error)
	NewEvent(context.Context, *NewEventRequest) (*domain.Response, error)
	GetPubFromPriv(context.Context, *GetPubFromPrivRequest) (*GetPubFromPrivResponse, error)
	GetNameFromPub(context.Context, *GetNameFromPubRequest) (*GetNameFromPubResponse, error)
	GetPubFromName(context.Context, *GetPubFromNameRequest) (*GetPubFromNameResponse, error)
}

// UnimplementedEOSServer can be embedded to have forward compatible implementations.
type UnimplementedEOSServer struct {
}

func (*UnimplementedEOSServer) NewEOSAccount(ctx context.Context, req *domain.Nil) (*domain.EosAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewEOSAccount not implemented")
}
func (*UnimplementedEOSServer) NewFacility(ctx context.Context, req *domain.Facility) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewFacility not implemented")
}
func (*UnimplementedEOSServer) GetFacilityEOSName(ctx context.Context, req *domain.EosAccount) (*domain.Facility, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFacilityEOSName not implemented")
}
func (*UnimplementedEOSServer) GetFacilityByID(ctx context.Context, req *GetByIDRequest) (*domain.Facility, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFacilityByID not implemented")
}
func (*UnimplementedEOSServer) NewProduct(ctx context.Context, req *NewProductRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewProduct not implemented")
}
func (*UnimplementedEOSServer) DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedEOSServer) UpdateProductName(ctx context.Context, req *UpdateProductNameRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductName not implemented")
}
func (*UnimplementedEOSServer) GetProductByID(ctx context.Context, req *GetByIDRequest) (*domain.Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}
func (*UnimplementedEOSServer) NewProductItem(ctx context.Context, req *NewProductItemRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewProductItem not implemented")
}
func (*UnimplementedEOSServer) DeleteProductItem(ctx context.Context, req *DeleteProductItemRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductItem not implemented")
}
func (*UnimplementedEOSServer) GetProductItemByID(ctx context.Context, req *GetByIDRequest) (*domain.ProductItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductItemByID not implemented")
}
func (*UnimplementedEOSServer) NewProductImage(ctx context.Context, req *NewProductImageRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewProductImage not implemented")
}
func (*UnimplementedEOSServer) DeleteAllProductImages(ctx context.Context, req *DeleteAllProductImagesRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllProductImages not implemented")
}
func (*UnimplementedEOSServer) NewEvent(ctx context.Context, req *NewEventRequest) (*domain.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewEvent not implemented")
}
func (*UnimplementedEOSServer) GetPubFromPriv(ctx context.Context, req *GetPubFromPrivRequest) (*GetPubFromPrivResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPubFromPriv not implemented")
}
func (*UnimplementedEOSServer) GetNameFromPub(ctx context.Context, req *GetNameFromPubRequest) (*GetNameFromPubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNameFromPub not implemented")
}
func (*UnimplementedEOSServer) GetPubFromName(ctx context.Context, req *GetPubFromNameRequest) (*GetPubFromNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPubFromName not implemented")
}

func RegisterEOSServer(s *grpc.Server, srv EOSServer) {
	s.RegisterService(&_EOS_serviceDesc, srv)
}

func _EOS_NewEOSAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).NewEOSAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/NewEOSAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).NewEOSAccount(ctx, req.(*domain.Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_NewFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.Facility)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).NewFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/NewFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).NewFacility(ctx, req.(*domain.Facility))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_GetFacilityEOSName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.EosAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).GetFacilityEOSName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/GetFacilityEOSName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).GetFacilityEOSName(ctx, req.(*domain.EosAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_GetFacilityByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).GetFacilityByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/GetFacilityByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).GetFacilityByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_NewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).NewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/NewProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).NewProduct(ctx, req.(*NewProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_UpdateProductName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).UpdateProductName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/UpdateProductName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).UpdateProductName(ctx, req.(*UpdateProductNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/GetProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).GetProductByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_NewProductItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProductItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).NewProductItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/NewProductItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).NewProductItem(ctx, req.(*NewProductItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_DeleteProductItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).DeleteProductItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/DeleteProductItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).DeleteProductItem(ctx, req.(*DeleteProductItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_GetProductItemByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).GetProductItemByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/GetProductItemByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).GetProductItemByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_NewProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).NewProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/NewProductImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).NewProductImage(ctx, req.(*NewProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_DeleteAllProductImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllProductImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).DeleteAllProductImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/DeleteAllProductImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).DeleteAllProductImages(ctx, req.(*DeleteAllProductImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_NewEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).NewEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/NewEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).NewEvent(ctx, req.(*NewEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_GetPubFromPriv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPubFromPrivRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).GetPubFromPriv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/GetPubFromPriv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).GetPubFromPriv(ctx, req.(*GetPubFromPrivRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_GetNameFromPub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNameFromPubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).GetNameFromPub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/GetNameFromPub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).GetNameFromPub(ctx, req.(*GetNameFromPubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EOS_GetPubFromName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPubFromNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOSServer).GetPubFromName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.eos.EOS/GetPubFromName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOSServer).GetPubFromName(ctx, req.(*GetPubFromNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EOS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.eos.EOS",
	HandlerType: (*EOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewEOSAccount",
			Handler:    _EOS_NewEOSAccount_Handler,
		},
		{
			MethodName: "NewFacility",
			Handler:    _EOS_NewFacility_Handler,
		},
		{
			MethodName: "GetFacilityEOSName",
			Handler:    _EOS_GetFacilityEOSName_Handler,
		},
		{
			MethodName: "GetFacilityByID",
			Handler:    _EOS_GetFacilityByID_Handler,
		},
		{
			MethodName: "NewProduct",
			Handler:    _EOS_NewProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _EOS_DeleteProduct_Handler,
		},
		{
			MethodName: "UpdateProductName",
			Handler:    _EOS_UpdateProductName_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _EOS_GetProductByID_Handler,
		},
		{
			MethodName: "NewProductItem",
			Handler:    _EOS_NewProductItem_Handler,
		},
		{
			MethodName: "DeleteProductItem",
			Handler:    _EOS_DeleteProductItem_Handler,
		},
		{
			MethodName: "GetProductItemByID",
			Handler:    _EOS_GetProductItemByID_Handler,
		},
		{
			MethodName: "NewProductImage",
			Handler:    _EOS_NewProductImage_Handler,
		},
		{
			MethodName: "DeleteAllProductImages",
			Handler:    _EOS_DeleteAllProductImages_Handler,
		},
		{
			MethodName: "NewEvent",
			Handler:    _EOS_NewEvent_Handler,
		},
		{
			MethodName: "GetPubFromPriv",
			Handler:    _EOS_GetPubFromPriv_Handler,
		},
		{
			MethodName: "GetNameFromPub",
			Handler:    _EOS_GetNameFromPub_Handler,
		},
		{
			MethodName: "GetPubFromName",
			Handler:    _EOS_GetPubFromName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/eos/eos.proto",
}
