// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain/domain.proto

package domain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FacilityType int32

const (
	FacilityType_FARMER       FacilityType = 0
	FacilityType_SUPPLIER     FacilityType = 1
	FacilityType_FACTORY      FacilityType = 2
	FacilityType_DISTRIBUTION FacilityType = 3
	FacilityType_RETAIL       FacilityType = 4
	FacilityType_CUSTOMER     FacilityType = 5
)

var FacilityType_name = map[int32]string{
	0: "FARMER",
	1: "SUPPLIER",
	2: "FACTORY",
	3: "DISTRIBUTION",
	4: "RETAIL",
	5: "CUSTOMER",
}

var FacilityType_value = map[string]int32{
	"FARMER":       0,
	"SUPPLIER":     1,
	"FACTORY":      2,
	"DISTRIBUTION": 3,
	"RETAIL":       4,
	"CUSTOMER":     5,
}

func (x FacilityType) String() string {
	return proto.EnumName(FacilityType_name, int32(x))
}

func (FacilityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{0}
}

type EosAccount struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrivateKey           string   `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosAccount) Reset()         { *m = EosAccount{} }
func (m *EosAccount) String() string { return proto.CompactTextString(m) }
func (*EosAccount) ProtoMessage()    {}
func (*EosAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{0}
}

func (m *EosAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosAccount.Unmarshal(m, b)
}
func (m *EosAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosAccount.Marshal(b, m, deterministic)
}
func (m *EosAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosAccount.Merge(m, src)
}
func (m *EosAccount) XXX_Size() int {
	return xxx_messageInfo_EosAccount.Size(m)
}
func (m *EosAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EosAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EosAccount proto.InternalMessageInfo

func (m *EosAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EosAccount) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *EosAccount) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type QueryOrder struct {
	OrderField           string   `protobuf:"bytes,1,opt,name=order_field,json=orderField,proto3" json:"order_field,omitempty"`
	OrderBy              string   `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrder) Reset()         { *m = QueryOrder{} }
func (m *QueryOrder) String() string { return proto.CompactTextString(m) }
func (*QueryOrder) ProtoMessage()    {}
func (*QueryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{1}
}

func (m *QueryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrder.Unmarshal(m, b)
}
func (m *QueryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrder.Marshal(b, m, deterministic)
}
func (m *QueryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrder.Merge(m, src)
}
func (m *QueryOrder) XXX_Size() int {
	return xxx_messageInfo_QueryOrder.Size(m)
}
func (m *QueryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrder proto.InternalMessageInfo

func (m *QueryOrder) GetOrderField() string {
	if m != nil {
		return m.OrderField
	}
	return ""
}

func (m *QueryOrder) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type Pagination struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{2}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Pagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Facility struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EosUsername          string   `protobuf:"bytes,3,opt,name=eos_username,json=eosUsername,proto3" json:"eos_username,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Location             string   `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Website              string   `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Facility) Reset()         { *m = Facility{} }
func (m *Facility) String() string { return proto.CompactTextString(m) }
func (*Facility) ProtoMessage()    {}
func (*Facility) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{3}
}

func (m *Facility) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facility.Unmarshal(m, b)
}
func (m *Facility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facility.Marshal(b, m, deterministic)
}
func (m *Facility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facility.Merge(m, src)
}
func (m *Facility) XXX_Size() int {
	return xxx_messageInfo_Facility.Size(m)
}
func (m *Facility) XXX_DiscardUnknown() {
	xxx_messageInfo_Facility.DiscardUnknown(m)
}

var xxx_messageInfo_Facility proto.InternalMessageInfo

func (m *Facility) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Facility) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Facility) GetEosUsername() string {
	if m != nil {
		return m.EosUsername
	}
	return ""
}

func (m *Facility) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Facility) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Facility) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Facility) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Facility) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FacilityId           string   `protobuf:"bytes,4,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{4}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Product) GetFacilityId() string {
	if m != nil {
		return m.FacilityId
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Product) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type ProductItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price                int32    `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	FromProductItemId    string   `protobuf:"bytes,4,opt,name=from_product_item_id,json=fromProductItemId,proto3" json:"from_product_item_id,omitempty"`
	ExpiryDateTimestamp  int64    `protobuf:"varint,5,opt,name=expiry_date_timestamp,json=expiryDateTimestamp,proto3" json:"expiry_date_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductItem) Reset()         { *m = ProductItem{} }
func (m *ProductItem) String() string { return proto.CompactTextString(m) }
func (*ProductItem) ProtoMessage()    {}
func (*ProductItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{5}
}

func (m *ProductItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductItem.Unmarshal(m, b)
}
func (m *ProductItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductItem.Marshal(b, m, deterministic)
}
func (m *ProductItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductItem.Merge(m, src)
}
func (m *ProductItem) XXX_Size() int {
	return xxx_messageInfo_ProductItem.Size(m)
}
func (m *ProductItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProductItem proto.InternalMessageInfo

func (m *ProductItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductItem) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ProductItem) GetFromProductItemId() string {
	if m != nil {
		return m.FromProductItemId
	}
	return ""
}

func (m *ProductItem) GetExpiryDateTimestamp() int64 {
	if m != nil {
		return m.ExpiryDateTimestamp
	}
	return 0
}

type ProductImage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ImageId              string   `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductImage) Reset()         { *m = ProductImage{} }
func (m *ProductImage) String() string { return proto.CompactTextString(m) }
func (*ProductImage) ProtoMessage()    {}
func (*ProductImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{6}
}

func (m *ProductImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductImage.Unmarshal(m, b)
}
func (m *ProductImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductImage.Marshal(b, m, deterministic)
}
func (m *ProductImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductImage.Merge(m, src)
}
func (m *ProductImage) XXX_Size() int {
	return xxx_messageInfo_ProductImage.Size(m)
}
func (m *ProductImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductImage.DiscardUnknown(m)
}

var xxx_messageInfo_ProductImage proto.InternalMessageInfo

func (m *ProductImage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductImage) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductImage) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

type Event struct {
	Id                    string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductItemId         string   `protobuf:"bytes,2,opt,name=product_item_id,json=productItemId,proto3" json:"product_item_id,omitempty"`
	Name                  string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt             int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FromFacilityId        string   `protobuf:"bytes,5,opt,name=from_facility_id,json=fromFacilityId,proto3" json:"from_facility_id,omitempty"`
	ToFacilityId          string   `protobuf:"bytes,6,opt,name=to_facility_id,json=toFacilityId,proto3" json:"to_facility_id,omitempty"`
	DeliveredByFacilityId string   `protobuf:"bytes,7,opt,name=delivered_by_facility_id,json=deliveredByFacilityId,proto3" json:"delivered_by_facility_id,omitempty"`
	SoldAt                int64    `protobuf:"varint,8,opt,name=sold_at,json=soldAt,proto3" json:"sold_at,omitempty"`
	FromProductItemId     string   `protobuf:"bytes,9,opt,name=from_product_item_id,json=fromProductItemId,proto3" json:"from_product_item_id,omitempty"`
	ToProductItemId       string   `protobuf:"bytes,10,opt,name=to_product_item_id,json=toProductItemId,proto3" json:"to_product_item_id,omitempty"`
	Quality               int32    `protobuf:"varint,11,opt,name=quality,proto3" json:"quality,omitempty"`
	ProductItemIds        []string `protobuf:"bytes,12,rep,name=product_item_ids,json=productItemIds,proto3" json:"product_item_ids,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{7}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetProductItemId() string {
	if m != nil {
		return m.ProductItemId
	}
	return ""
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Event) GetFromFacilityId() string {
	if m != nil {
		return m.FromFacilityId
	}
	return ""
}

func (m *Event) GetToFacilityId() string {
	if m != nil {
		return m.ToFacilityId
	}
	return ""
}

func (m *Event) GetDeliveredByFacilityId() string {
	if m != nil {
		return m.DeliveredByFacilityId
	}
	return ""
}

func (m *Event) GetSoldAt() int64 {
	if m != nil {
		return m.SoldAt
	}
	return 0
}

func (m *Event) GetFromProductItemId() string {
	if m != nil {
		return m.FromProductItemId
	}
	return ""
}

func (m *Event) GetToProductItemId() string {
	if m != nil {
		return m.ToProductItemId
	}
	return ""
}

func (m *Event) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *Event) GetProductItemIds() []string {
	if m != nil {
		return m.ProductItemIds
	}
	return nil
}

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{8}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9b353c0ddff1198, []int{9}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterEnum("domain.FacilityType", FacilityType_name, FacilityType_value)
	proto.RegisterType((*EosAccount)(nil), "domain.EosAccount")
	proto.RegisterType((*QueryOrder)(nil), "domain.QueryOrder")
	proto.RegisterType((*Pagination)(nil), "domain.Pagination")
	proto.RegisterType((*Facility)(nil), "domain.Facility")
	proto.RegisterType((*Product)(nil), "domain.Product")
	proto.RegisterType((*ProductItem)(nil), "domain.ProductItem")
	proto.RegisterType((*ProductImage)(nil), "domain.ProductImage")
	proto.RegisterType((*Event)(nil), "domain.Event")
	proto.RegisterType((*Nil)(nil), "domain.Nil")
	proto.RegisterType((*Response)(nil), "domain.Response")
}

func init() { proto.RegisterFile("domain/domain.proto", fileDescriptor_c9b353c0ddff1198) }

var fileDescriptor_c9b353c0ddff1198 = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5d, 0xaf, 0xdb, 0x44,
	0x10, 0x25, 0xf1, 0x75, 0xec, 0x3b, 0x09, 0xb7, 0x61, 0xfb, 0x81, 0x8b, 0x84, 0xb8, 0x58, 0x08,
	0x55, 0x20, 0x51, 0x09, 0x1e, 0x78, 0x4e, 0xda, 0x44, 0x58, 0x2d, 0x49, 0xf0, 0x4d, 0x24, 0xe0,
	0xc5, 0x6c, 0xec, 0x49, 0x59, 0x61, 0x7b, 0x8d, 0x77, 0x9d, 0x62, 0x7e, 0x18, 0x3f, 0x81, 0x37,
	0xde, 0xf8, 0x41, 0x68, 0x3f, 0x9c, 0x3a, 0xf7, 0xaa, 0x12, 0x7d, 0xca, 0x9e, 0x73, 0x76, 0xc6,
	0x73, 0x66, 0x26, 0x36, 0xdc, 0xcf, 0x78, 0x41, 0x59, 0xf9, 0xd4, 0xfc, 0x7c, 0x55, 0xd5, 0x5c,
	0x72, 0x32, 0x32, 0x28, 0xfc, 0x05, 0x60, 0xc1, 0xc5, 0x2c, 0x4d, 0x79, 0x53, 0x4a, 0x42, 0xe0,
	0xa2, 0xa4, 0x05, 0x06, 0x83, 0xeb, 0xc1, 0x93, 0xcb, 0x58, 0x9f, 0xc9, 0x27, 0x30, 0xae, 0x6a,
	0x76, 0xa4, 0x12, 0x93, 0xdf, 0xb0, 0x0d, 0x86, 0x5a, 0x02, 0x4b, 0xbd, 0xc0, 0x96, 0x7c, 0x0c,
	0x50, 0x35, 0xfb, 0x9c, 0xa5, 0x5a, 0x77, 0xb4, 0x7e, 0x69, 0x98, 0x17, 0xd8, 0x86, 0xdf, 0x01,
	0xfc, 0xd0, 0x60, 0xdd, 0xae, 0xeb, 0x0c, 0x6b, 0x95, 0x8d, 0xab, 0x43, 0x72, 0x60, 0x98, 0x67,
	0xf6, 0x41, 0xa0, 0xa9, 0xa5, 0x62, 0xc8, 0x63, 0xf0, 0xcd, 0x85, 0x7d, 0xf7, 0x2c, 0x4f, 0xe3,
	0x79, 0x1b, 0xae, 0x00, 0x36, 0xf4, 0x15, 0x2b, 0xa9, 0x64, 0xbc, 0x24, 0x8f, 0x60, 0xc4, 0x0f,
	0x07, 0x81, 0x52, 0x27, 0x71, 0x63, 0x8b, 0xc8, 0x03, 0x70, 0x73, 0x56, 0x30, 0xa9, 0xa3, 0xdd,
	0xd8, 0x00, 0xe5, 0x4c, 0xb0, 0x3f, 0x51, 0x97, 0xe7, 0xc6, 0xfa, 0x1c, 0xfe, 0x3b, 0x00, 0x7f,
	0x49, 0x53, 0x96, 0x33, 0xd9, 0x92, 0x2b, 0x18, 0xb2, 0xae, 0x9e, 0x21, 0xcb, 0x4e, 0xad, 0x18,
	0xf6, 0x5a, 0xf1, 0x29, 0x4c, 0x90, 0x8b, 0xa4, 0x11, 0x58, 0x6b, 0xcd, 0x78, 0x1d, 0x23, 0x17,
	0x3b, 0x4b, 0xa9, 0x30, 0xd9, 0x56, 0x18, 0x5c, 0x98, 0x30, 0x75, 0x56, 0x15, 0x61, 0x41, 0x59,
	0x1e, 0xb8, 0x9a, 0x34, 0x40, 0x25, 0xab, 0x7e, 0xe5, 0x25, 0x26, 0x65, 0x53, 0xec, 0xb1, 0x0e,
	0x46, 0x26, 0x99, 0xe6, 0x56, 0x9a, 0x22, 0x1f, 0x81, 0x9f, 0xf3, 0x54, 0xdb, 0x0d, 0x3c, 0x2d,
	0x9f, 0x30, 0x09, 0xc0, 0x7b, 0x8d, 0x7b, 0xc1, 0x24, 0x06, 0xbe, 0x69, 0x93, 0x85, 0xe1, 0xdf,
	0x03, 0xf0, 0x36, 0x35, 0xcf, 0x9a, 0x54, 0xfe, 0x2f, 0x57, 0x8f, 0x60, 0x44, 0x8f, 0x54, 0xd2,
	0xda, 0xfa, 0xb1, 0x48, 0x8d, 0xea, 0x60, 0xbb, 0x93, 0xb0, 0xcc, 0x3a, 0x82, 0x8e, 0x8a, 0x32,
	0x72, 0x0d, 0xe3, 0x0c, 0x45, 0x5a, 0xb3, 0x4a, 0x57, 0x68, 0x0d, 0xf4, 0x28, 0xb5, 0x1a, 0x69,
	0x8d, 0x54, 0x62, 0x96, 0x50, 0xa9, 0x2d, 0x38, 0xf1, 0xa5, 0x65, 0x66, 0x52, 0xc9, 0x4d, 0x95,
	0x75, 0xb2, 0x6f, 0x64, 0xcb, 0xcc, 0x64, 0xf8, 0xcf, 0x00, 0xc6, 0xd6, 0x48, 0x24, 0xb1, 0xb8,
	0x63, 0x46, 0x2d, 0x9e, 0x91, 0x55, 0x7d, 0x43, 0xbb, 0x78, 0x36, 0x20, 0x53, 0x6d, 0xaf, 0x6a,
	0x96, 0xa2, 0x2e, 0xcc, 0x8d, 0x0d, 0x50, 0x2c, 0x7f, 0x5d, 0x62, 0x67, 0xd6, 0x00, 0xf2, 0x14,
	0x1e, 0x1c, 0x6a, 0x5e, 0x24, 0xa7, 0x7c, 0x12, 0x8b, 0x37, 0xa6, 0x3f, 0x50, 0x5a, 0xaf, 0x92,
	0x28, 0x23, 0x5f, 0xc3, 0x43, 0xfc, 0xa3, 0x62, 0x75, 0x9b, 0xa8, 0x6a, 0x13, 0xc9, 0x0a, 0x14,
	0x92, 0x16, 0x95, 0x9e, 0xb1, 0x13, 0xdf, 0x37, 0xe2, 0x73, 0x2a, 0x71, 0xdb, 0x49, 0xe1, 0x8f,
	0x30, 0xe9, 0x92, 0x14, 0xf4, 0x15, 0xbe, 0xab, 0x9f, 0xc7, 0xe0, 0x33, 0x15, 0xa7, 0x44, 0x53,
	0xbc, 0xa7, 0x71, 0x94, 0x85, 0x7f, 0x39, 0xe0, 0x2e, 0x8e, 0x58, 0xde, 0x1d, 0xf8, 0xe7, 0x70,
	0xef, 0xb6, 0x27, 0x93, 0xf8, 0xfd, 0xea, 0xcc, 0x4f, 0xb7, 0x18, 0x4e, 0x6f, 0x31, 0xce, 0xa7,
	0x77, 0x71, 0x7b, 0x7a, 0x4f, 0x60, 0xaa, 0x7b, 0xd6, 0x5f, 0x12, 0xb3, 0xe1, 0x57, 0x8a, 0x5f,
	0xbe, 0x59, 0x94, 0xcf, 0xe0, 0x4a, 0xf2, 0xb3, 0x7b, 0x66, 0x57, 0x26, 0x92, 0xf7, 0x6e, 0x7d,
	0x0b, 0x41, 0x86, 0x39, 0x3b, 0x62, 0x8d, 0x59, 0xb2, 0x6f, 0xcf, 0xee, 0x9b, 0xed, 0x7f, 0x78,
	0xd2, 0xe7, 0x6d, 0x2f, 0xf0, 0x43, 0xf0, 0x04, 0xcf, 0x7b, 0x3b, 0x34, 0x52, 0x70, 0x26, 0xdf,
	0x3a, 0xd5, 0xcb, 0xb7, 0x4d, 0xf5, 0x4b, 0x20, 0x92, 0xdf, 0xb9, 0x0e, 0xfa, 0xfa, 0x3d, 0xc9,
	0xcf, 0x2f, 0x07, 0xe0, 0xfd, 0xde, 0x50, 0x55, 0x43, 0x30, 0xd6, 0x1b, 0xd6, 0x41, 0xd5, 0x99,
	0x5b, 0x39, 0x44, 0x30, 0xb9, 0x76, 0x54, 0x67, 0xce, 0xba, 0x2e, 0x42, 0x17, 0x9c, 0x15, 0xcb,
	0xc3, 0x10, 0xfc, 0x18, 0x45, 0xc5, 0x4b, 0xa1, 0xff, 0x8e, 0x42, 0x52, 0xd9, 0x88, 0xee, 0xbd,
	0x66, 0xd0, 0x17, 0x14, 0x26, 0x9d, 0xe7, 0xad, 0x7a, 0xab, 0x00, 0x8c, 0x96, 0xb3, 0xf8, 0xfb,
	0x45, 0x3c, 0x7d, 0x8f, 0x4c, 0xc0, 0xbf, 0xd9, 0x6d, 0x36, 0x2f, 0xa3, 0x45, 0x3c, 0x1d, 0x90,
	0x31, 0x78, 0xcb, 0xd9, 0xb3, 0xed, 0x3a, 0xfe, 0x69, 0x3a, 0x24, 0x53, 0x98, 0x3c, 0x8f, 0x6e,
	0xb6, 0x71, 0x34, 0xdf, 0x6d, 0xa3, 0xf5, 0x6a, 0xea, 0xa8, 0xc0, 0x78, 0xb1, 0x9d, 0x45, 0x2f,
	0xa7, 0x17, 0x2a, 0xf0, 0xd9, 0xee, 0x66, 0xbb, 0x56, 0x69, 0xdc, 0xb9, 0xff, 0xb3, 0xfd, 0x2c,
	0xec, 0x47, 0xfa, 0x2b, 0xf1, 0xcd, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x37, 0xe2, 0xf9,
	0x3c, 0x06, 0x00, 0x00,
}
