version: "3"

# networks:
#   eos:
#     driver: bridge
#     ipam:
#      config:
#        - subnet: 10.7.0.0/16

services:
  db:
    image: mongo:4.2.1
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: EOSweb
    # networks:
    #   eos:
    #     ipv4_address: 10.7.0.5
  
  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: test123
    # networks:
    #   eos:
    #     ipv4_address: 10.7.0.4

  eosweb:
    image: eosweb:latest
    # image: rost1337/eosweb:latest
    ports: 
      - 3039:3039
      - 9615:9615
    restart: always
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./config.js:/home/eosweb/config.js
    # networks:
    #   eos:
    #     ipv4_address: 10.7.0.6
