// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/main/facility/facility.proto

package facility

import (
	context "context"
	fmt "fmt"
	math "math"

	domain "main_service/config/grpc/proto/domain"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetFacilitiesRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFacilitiesRequest) Reset()         { *m = GetFacilitiesRequest{} }
func (m *GetFacilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetFacilitiesRequest) ProtoMessage()    {}
func (*GetFacilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8485bda72a9e46f7, []int{0}
}

func (m *GetFacilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFacilitiesRequest.Unmarshal(m, b)
}
func (m *GetFacilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFacilitiesRequest.Marshal(b, m, deterministic)
}
func (m *GetFacilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFacilitiesRequest.Merge(m, src)
}
func (m *GetFacilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetFacilitiesRequest.Size(m)
}
func (m *GetFacilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFacilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFacilitiesRequest proto.InternalMessageInfo

func (m *GetFacilitiesRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetFacilitiesResponse struct {
	Facilities           []*domain.Facility `protobuf:"bytes,1,rep,name=facilities,proto3" json:"facilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetFacilitiesResponse) Reset()         { *m = GetFacilitiesResponse{} }
func (m *GetFacilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetFacilitiesResponse) ProtoMessage()    {}
func (*GetFacilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8485bda72a9e46f7, []int{1}
}

func (m *GetFacilitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFacilitiesResponse.Unmarshal(m, b)
}
func (m *GetFacilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFacilitiesResponse.Marshal(b, m, deterministic)
}
func (m *GetFacilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFacilitiesResponse.Merge(m, src)
}
func (m *GetFacilitiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetFacilitiesResponse.Size(m)
}
func (m *GetFacilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFacilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFacilitiesResponse proto.InternalMessageInfo

func (m *GetFacilitiesResponse) GetFacilities() []*domain.Facility {
	if m != nil {
		return m.Facilities
	}
	return nil
}

func init() {
	proto.RegisterType((*GetFacilitiesRequest)(nil), "service.main.facility.GetFacilitiesRequest")
	proto.RegisterType((*GetFacilitiesResponse)(nil), "service.main.facility.GetFacilitiesResponse")
}

func init() {
	proto.RegisterFile("service/main/facility/facility.proto", fileDescriptor_8485bda72a9e46f7)
}

var fileDescriptor_8485bda72a9e46f7 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x4f, 0x4b, 0x4c, 0xce, 0xcc, 0xc9, 0x2c,
	0xa9, 0x84, 0x33, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x44, 0xa1, 0xaa, 0xf4, 0x40, 0xaa,
	0xf4, 0x60, 0x92, 0x52, 0xc2, 0x29, 0xf9, 0x60, 0x6d, 0x10, 0x0a, 0xa2, 0x56, 0x49, 0x8b, 0x4b,
	0xc4, 0x3d, 0xb5, 0xc4, 0x0d, 0xa2, 0x26, 0x33, 0xb5, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8,
	0x44, 0x48, 0x88, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xcc, 0x56, 0xf2, 0xe4, 0x12, 0x45, 0x53, 0x5b, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xc0,
	0xc5, 0x95, 0x06, 0x17, 0x95, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd0, 0x83, 0xda, 0x03,
	0x55, 0x5f, 0x19, 0x84, 0xa4, 0xc6, 0xa8, 0x8c, 0x8b, 0x03, 0x26, 0x2e, 0x94, 0xc5, 0xc5, 0x8b,
	0x62, 0xac, 0x90, 0xb6, 0x1e, 0x56, 0x0f, 0xe8, 0x61, 0x73, 0xa8, 0x94, 0x0e, 0x71, 0x8a, 0x21,
	0x2e, 0x75, 0xe2, 0x8a, 0xe2, 0x80, 0xa9, 0x48, 0x62, 0x03, 0x87, 0x80, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x3e, 0x68, 0x61, 0x12, 0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FacilityClient is the client API for Facility service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FacilityClient interface {
	GetFacilities(ctx context.Context, in *GetFacilitiesRequest, opts ...grpc.CallOption) (*GetFacilitiesResponse, error)
}

type facilityClient struct {
	cc *grpc.ClientConn
}

func NewFacilityClient(cc *grpc.ClientConn) FacilityClient {
	return &facilityClient{cc}
}

func (c *facilityClient) GetFacilities(ctx context.Context, in *GetFacilitiesRequest, opts ...grpc.CallOption) (*GetFacilitiesResponse, error) {
	out := new(GetFacilitiesResponse)
	err := c.cc.Invoke(ctx, "/service.main.facility.Facility/GetFacilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacilityServer is the server API for Facility service.
type FacilityServer interface {
	GetFacilities(context.Context, *GetFacilitiesRequest) (*GetFacilitiesResponse, error)
}

// UnimplementedFacilityServer can be embedded to have forward compatible implementations.
type UnimplementedFacilityServer struct {
}

func (*UnimplementedFacilityServer) GetFacilities(ctx context.Context, req *GetFacilitiesRequest) (*GetFacilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFacilities not implemented")
}

func RegisterFacilityServer(s *grpc.Server, srv FacilityServer) {
	s.RegisterService(&_Facility_serviceDesc, srv)
}

func _Facility_GetFacilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFacilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServer).GetFacilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.main.facility.Facility/GetFacilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServer).GetFacilities(ctx, req.(*GetFacilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Facility_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.main.facility.Facility",
	HandlerType: (*FacilityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFacilities",
			Handler:    _Facility_GetFacilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/main/facility/facility.proto",
}
