version: '3'
services:
  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_USER: '${POSTGREST_DB_USER}'
      POSTGRES_PASSWORD: '${POSTGREST_DB_PASSWORD}'
      POSTGRES_DB: '${POSTGREST_DB_NAME}'
    # volumes:
    #   - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pappu687
      ADMINER_DEFAULT_SERVER: postgresql